dist: bionic

language: python

sudo: required

before_install:
  - sudo apt-get install -y pylint3

script:
  - sudo make install
  - sudo make systemd

  - make pylint

  - oom-sort -h
  - oom-sort

  - nohang -h
  - nohang -v

  - nohang -cc /etc/nohang/nohang.conf
  - nohang -cc test.conf

  - nohang -p
  - sudo nohang -p

  - sudo bash -c "nohang & tail /dev/zero & sleep 20 && pkill python3"

  - /bin/sleep 60 &
  - sudo bash -c "nohang -c test.conf & tail /dev/zero & sleep 30 && pkill python3"
  - sudo cat /var/log/nohang/nohang.log

  - sudo make uninstall
